### ISSUE TITLE
CTCModule GUIMap null pointer exception

### ISSUE THREAD

**Issue by eap85** [Jchuk99/Team-A#37]
Subject of the issue
GUIMap is trying to build with no nodes being added.

Priority: 

Module and Version:

Is it an interface issue? If so, with what other modules?: 

Steps to reproduce: Tell us how to reproduce this issue. 

Expected behaviour: Tell us what should happen

Actual behaviour: Tell us what happens instead

Inspired by https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Jchuk99** [comment]
Waysides were not being create and weren't giving the blocks to the CTC, issue is fixed.
